/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library2 {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("test 2 all are work");
    }
}
